version: '3'

services:
  juypterhub:
    build: .
    container_name: dsastarhub
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    container_name: dsastarhub-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf