version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # - jupyterhub
      - eclipse-che
  # jupyterhub:
  #   # build: .
  #   image: jupyterhub/jupyterhub:latest
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./src/juypterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
  eclipse-che:
    image: eclipse/che
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/data:/data
    environment:
      - CHE_MULTIUSER=true
      - CHE_HOST=eclipse-che
    command: start
