version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jupyterhub
  jupyterhub:
    # build: .
    image: jupyterhub/jupyterhub:latest
    ports:
      - 8000:8000
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
  # hub:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - 
